+bids/report.m

Here is the adapted version of the bids_report funtion from the BIDS starter kit.
One part of the function still has a call to spm_vol if we want try to get data from the header.

Bids report

---

README.md

Add reference to other tool #7

Readme update: Add converter and viewer

---

README.md

I think #22 has established what versions are supported. How about documenting the system requirements in the README?
Closes #22.

README: Document requirements

---

+bids/+util/tsvread.m
+bids/layout.m

@gllmflndn 
Nothing huge but I kept getting headaches from all the short variable names and some of the deep nesting so I did made some small changes that hopefully should make things more transparent for newcomers.

Refactoring and renaming

---

+bids/+util/tsvread.m
+bids/private/file_utils.m
+bids/private/parse_filename.m
+bids/query.m
+bids/report.m
+bids/validate.m

@apjanke I could not do a clean rebase on your PR #27 so I am opening another PR to add your fixes here. :-)

Fix or suppress M-lint code inspection warnings

---

+bids/+util/tsvwrite.m
tests/test_tsvwrite.m

aims to fix #73 
at the moment only contains the failing test

[FIX] fix writing nan issues when dealing with arrays

---

.editorconfig

What do you think about adding an `.editorconfig` file to make it easier for contributors to stick to the repo's style guidelines?

Add .editorconfig?

---

.github/workflows/update_schema.yml
.gitignore
CONTRIBUTING.md
convert_schema.py
requirements.txt
schema/README.md
schema/associated_data.json
schema/auxdatatypes/channels.json
schema/auxdatatypes/electrodes.json
schema/auxdatatypes/events.json
schema/auxdatatypes/photo.json
schema/datatypes/anat.json
schema/datatypes/beh.json
schema/datatypes/dwi.json
schema/datatypes/eeg.json
schema/datatypes/fmap.json
schema/datatypes/func.json
schema/datatypes/ieeg.json
schema/datatypes/meg.json
schema/entities.json
schema/modalities.json
schema/top_level_files.json

[INFRA] conversion BIDS schema to json

---

+bids/+internal/append_to_layout.m
+bids/layout.m
+bids/query.m
tests/test_bids_query.m
tests/test_bids_query_eeg.m
tests/test_layout_derivatives.m

fixes #142 
should also address #97

[ENH] schemaless layout indexes json files

---

schema/datatypes/eeg.json
schema/datatypes/ieeg.json

Not entirely clear why I am getting the schema updates on my repo and not on the upstream... :shrug:

[INFRA] BIDS schema update

---

CONTRIBUTING.md
tests/README.md

@nbeliy let me know if that provides enough guidance to install MoxUnit.

[DOC] update instructions to run the tests

---

+bids/+internal/camel_case.m
+bids/+util/mkdir.m
+bids/derivatives_json.m
+bids/init.m
templates/README
templates/README.md
templates/README_datalad
tests/.gitignore
tests/test_bids_description.m
tests/test_bids_init.m
tests/test_copy_to_derivative.m

[ENH] add basic capabilities to initialize a dataset

---

+bids/+util/jsondecode.m
+bids/+util/jsonencode.m
+bids/+util/mkdir.m
+bids/+util/tsvread.m
+bids/+util/tsvwrite.m
+bids/Contents.m
+bids/copy_to_derivative.m
+bids/create_filename.m
+bids/derivatives_json.m
+bids/layout.m
+bids/query.m
+bids/report.m
+bids/validate.m
docs/source/function_description.rst
docs/source/index.rst

- set up doc
- clean help sections to prevent doc building failure

[DOC] set up sphinx and read the docs 

---

+bids/copy_to_derivative.m
+bids/layout.m
+bids/report.m
tests/test_layout_derivatives.m

- layout can now index nested derivatives ; fixes #146 
- minor change of `BIDS.dir` into `BIDS.pth` ; fixes #213

[ENH] Index nested derivatives

---

+bids/copy_to_derivative.m
tests/test_copy_to_derivative.m
tests/utils/set_test_cfg.m

[FIX] copy to derivatives for windows

---

+bids/+util/jsonencode.m
+bids/+util/jsonwrite.m
+bids/+util/miss_hit.cfg

extremely simplified the jsonencode.m that now call the imported jsonwrite.m function (modified to prettyPrint by default) - that way we always create a nice looking json file

Dev - jsonwrite by default

---

.github/workflows/run_tests_matlab.yml
.github/workflows/run_tests_octave.yml

Silence codecov until #115 is sorted because this adds unnecessary noise in the repo.

[INFRA] silence codecov

---

+bids/+internal/is_github_ci.m
tests/test_copy_to_derivative.m
tests/test_tsvread.m

closes #208 
make use of regex based filters used by query and implemented in #286

[TEST] add test for copying to derivatives with an exclude filter

---

+bids/File.m
tests/test_bids_file.m
tests/tests_query/test_bids_query.m

[ENH] validate entity keys provided when using BIDS schema to create filenames

---

tests/tests_query/test_bids_query.m
tests/tests_query/test_bids_query_matlab_octave.m

[INFRA] test for matlab octave difference

---

+bids/File.m
tests/test_bids_file.m

[ENH] apply camel case to "invalid" bids entities and add rename methods

---

CITATION.cff
README.md

Adding ORCID numbers so they can show up on [our zenodo page](https://zenodo.org/record/5910585) on the next release
---
@gllmflndn @CPernet @ChristophePhillips @cMadan @robertoostenveld @mnoergaard @HenkMutsaerts 
Can you cross check that I got yours right?
---
@nbeliy @tanguyduval @apjanke @mslw 
I could not find yours, so let me know what it is or add it yourself (if you have one).

[DOC] add orcid numbers to CITATION.CFF

---

+bids/+internal/append_to_layout.m
+bids/+util/tsvread.m
+bids/Schema.m
tests/tests_private/test_append_to_layout.m
tests/tests_utils/test_tsvread.m

[FIX] Skip missing suffix subgroup

---

+bids/File.m
tests/test_bids_file.m

[FIX] add test to catch error for invalid entities

---

+bids/Description.m
+bids/layout.m
tests/tests_layout/test_layout.m

- allow bids.Description to read directly from a file
fix bug that would cause an error when running layout in schema less mode on a dataset with empty subject directories

[ENH] improve bids.Description constructor

---

+bids/+internal/download.m
+bids/+internal/format_path.m
+bids/+util/download_ds.m
+bids/copy_to_derivative.m
+bids/layout.m

could otherwise lead to some warning about escaping characters.

[FIX] fix printing of windows path

---

.github/workflows/update_schema.yml

[INFRA] update PR content and title for schema update

---

+bids/query.m
tests/tests_query/test_query_bug_453.m

[FIX]  query with empty subject should return empty and not fail

---

+bids/+internal/return_file_index.m
+bids/layout.m

[FIX] add try catch for rare errors on invalid bids datasets

---

+bids/derivatives_json.m
tests/test_derivatives_json.m

[FIX] handle create derivatives metadata when some entity labels are just a number

---

+bids/init.m
demos/spm/facerep/code/spm_facerep.m
tests/test_bids_init.m

[ENH] validate folder name in bids.init

---

+bids/layout.m
demos/spm/facerep/code/spm_facerep.m

- add field in layout to flag datalad datasets
- limit warning when indexing dependencies in datalad datasets
relates to #477

[ENH] better handling of datalad datasets

---

+bids/+internal/plot_diagnostic_table.m
+bids/diagnostic.m
+bids/report.m

[ENH] add flags to make some functions less verbose

---

+bids/+transformers_list/Label_identical_rows.m
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/dependabot.yml
.github/workflows/run_examples.yml
.github/workflows/tests.yml
.github/workflows/update_schema.yml
.github/workflows/validate.yml
.pre-commit-config.yaml
.readthedocs.yml
binder/environment.yml

[MAINT] add pre commit hooks

---

+bids/query.m
tests/tests_query/test_bids_query.m

[ENH] add query for participants

---

+bids/layout.m
tests/tests_query/test_bids_query.m
tests/tests_query/test_bids_query_asl.m
tests/tests_query/test_bids_query_derivatives.m
tests/tests_query/test_bids_query_dwi.m
tests/tests_query/test_bids_query_eeg.m
tests/tests_query/test_bids_query_fmap.m
tests/tests_query/test_bids_query_func.m
tests/tests_query/test_bids_query_ieeg.m
tests/tests_query/test_bids_query_matlab_octave.m
tests/tests_query/test_bids_query_meg.m
tests/tests_query/test_bids_query_microscopy.m
tests/tests_query/test_bids_query_motion.m
tests/tests_query/test_bids_query_nirs.m
tests/tests_query/test_bids_query_qmri.m
tests/tests_query/test_query_bug_453.m

[ENH] add electrodes and optodes as group dependencies

---

+bids/layout.m
tests/tests_layout/test_layout.m
tests/tests_layout/test_layout_schemaless.m

[ENH] allow indexing of files missing session entity when schemaless

---

+bids/layout.m
+bids/query.m
tests/tests_query/test_bids_query.m

[ENH] index and query phenotype

---

+bids/+internal/keep_file_for_query.m
+bids/layout.m
tests/tests_layout/test_layout.m

[ENH] do not add subject to layout if it is empty

---

+bids/+internal/get_meta_list.m
+bids/+internal/get_metadata.m

- closes none
- related to #597

[ENH] use inheritance in get_meta_list

---

+bids/Schema.m
tests/test_bids_schema.m

- closes #608
- can return all entities for  datatype / suffix combination
- can return all suffixes for one or more datatype

[ENH] improve bids schema api

---

+bids/+util/create_data_dict.m
tests/tests_utils/test_create_data_dict.m

create_data_dict will now create objects for each level
See https://github.com/bids-standard/bids-specification/pull/1603

[ENH] use objects for levels

---

+bids/+internal/resolve_bids_uri.m
+bids/layout.m
tests/tests_private/test_resolve_bids_uri.m

[ENH] add internal function to start resolvig uri

---

.github/workflows/update_schema.yml

2. [ ] Have you lint your code locally prior to submission?

[MAINT] try removing token from update schema workflow

---

+bids/+internal/return_subject_index.m
+bids/layout.m
tests/tests_layout/test_layout_derivatives.m

[FIX] index modality at same level as sessions

---

+bids/+internal/list_all_trial_types.m
.github/workflows/validate.yml
.pre-commit-config.yaml
tests/test_bids_model.m

2. [ ] Have you lint your code locally prior to submission?

[FIX] ignore 'na' as trial types when creating default models

---

tests/tests_private/test_file_utils.m

2. [ ] Have you lint your code locally prior to submission?

[REF] minor refactor

---

.github/workflows/auto_merge.yml

2. [ ] Have you lint your code locally prior to submission?

[FIX] fix automerge

---

+bids/Schema.m
.github/workflows/run_tests_matlab.yml
.github/workflows/run_tests_octave.yml
tests/test_bids_schema.m
tests/tests_query/test_bids_query_mrs.m
tests/tests_query/test_bids_query_nirs.m

2. [x] Have you lint your code locally prior to submission?
---
Content:
- events suffixes were 'moved' of their datatypes by https://github.com/bids-standard/bids-specification/pull/1440
- they need to be added back 'manually' when checking the list of suffixes for a given datatype

[FIX] schema - add events to extra suffixes
