bids-standard/bids-matlab

+bids/+util/tsvread.m
+bids/layout.m
+bids/private/file_utils.m
+bids/private/parse_filename.m
+bids/query.m
tests/bids_runtests.m
tests/test_bids_examples.m

Here's a suggestion for more detailed error messages. This mostly involves including the actual problematic values in error messages, including a specific reason/underlying error message for a failure, or telling which BIDS file/dir it was trying to process when the error occurred. This will make it easier for users to diagnose errors when using BIDS-MATLAB.
It also switches to using the `catch <err>` syntax where appropriate. This syntax is supported by all Matlab and Octave versions indicated in https://github.com/bids-standard/bids-matlab/issues/22, and is more concise than calling `lasterror()`.

More detailed error messages

---

.gitignore

In the context of the CI runs, the bids-examples repo is downloaded and installed into `tests/`. It might be nice to support this workflow in local interactive usage, too. Adding it to the gitignore lets developers drop `bids-examples` in the same place as the test code is expecting it, without accidentally checking it into git on the main repo.

gitignore: ignore local copy of bids-examples

---

+bids/+util/jsondecode.m
+bids/+util/jsonencode.m

What do you think about supporting jsonencode/jsondecode when implemented as regular functions, in addition to just when they're built-ins? This would allow the jsonencode/jsondecode from jsonstuff (https://github.com/apjanke/octave-jsonstuff) or any other Matlab-compatible implementation to be used, in addition to JSONio. This would be nice for me because I'd rather use jsonstuff than JSONio. And there's a chance that jsonencode/jsondecode will eventually get merged into Octave core from one of these libraries, but might be regular functions instead of builtins there, so this would be forward-looking for future Octave versions. (Also, Matlab could always change the jsonencode/jsondecode implementation to use regular M-file wrapper functions, which would break the current detection.)

util: Support jsonencode/jsondecode as regular functions

---

+bids/query.m

Due to a quirk of how Matlab parses H1 lines in helptext, the word "Query" in the H1 line of query is being dropped in some contexts, like when you do `help bids` to see the contents listing of the `bids` package. This is because if the first word of the H1 line is the same name as the function, it's treated as the function name leading the H1 line, and not the first word of the function description. Here, it's meant to be the first word of the function description, acting as the function verb.
Before (in Matlab R2019b):
```
>> help bids
Contents of bids package:
layout - Parse a directory structure formated according to the bids standard
query - a directory structure formated according to the bids standard
```
This PR adds a second "QUERY" to the H1 line, so the second "Query" always …

Include QUERY in the H1 line for query's helptext

---

+bids/+util/tsvread.m
+bids/Contents.m
+bids/layout.m
+bids/query.m
+bids/report.m
+bids/validate.m

What do you think about making the per-function helptext more concise by concentrating the whole-library doco in a central `+bids/Contents.m` help file (that pops up when you do `help bids`)?
This way users can do `help bids` to get info on the overall library, and `help <fcn>` for the individual functions takes up less precious space in the command window. Each of the individual function help texts will have a link to the main `bids` help item so it'll be easy for users to find.
Works in Matlab R2014b-R2019b, though there's a bug in earlier versions of Matlab that causes the help for `help bids` to be displayed twice.

Make function helptext more concise with a +bids/Contents.m

---

+bids/private/get_metadata.m

Minor fix to let let BIDS-MATLAB handle the unusually-formatted metadata file in `eeg_face13` from the bids-example data set.
Fixes https://github.com/bids-standard/bids-matlab/issues/34.

Handle non-standard-format metadata JSON files

---

+bids/layout.m
+bids/private/parse_filename.m
+bids/report.m
+bids/validate.m

Just a few typo fixes. No functional changes.

Doc: Typo fixes in comments and helptext

---

+bids/+util/tsvwrite.m
tests/test_tsvwrite.m

Mentioned on the BIDS starter kit issue [#125](https://github.com/bids-standard/bids-starter-kit/issues/125) octave has trouble to save tables.
So this is a wrapper function mostly inspired from spm_save that could be used for both matlab and octave.

Create a tsvwrite function

---

+bids/+internal/README.md
+bids/+internal/file_utils.m
+bids/+internal/get_metadata.m
+bids/+internal/parse_filename.m
+bids/layout.m
+bids/query.m
.travis.yml

What do you think of moving the package-private functions in `+bids/private` to a new `+bids/+internal` package?
This would allow these functions to be directly tested and played with during development, but would still indicate to users of the library that they're for BIDS-MATLAB's internal use and shouldn't be called from client code. This "internal" package name is a pretty well-established convention these days. I've seen it in both Java and Matlab code, including MathWorks' own code.
This also removes the need to do the extra `addpath` step under Octave to work around its handling of `private` directories inside packages. This PR updates the `.travis.yml` file to reflect that.

Move +bids/private stuff to +bids/+internal?

---

.travis.yml

This will now use Octave 5.2.0 for tests.

[INFRA] Use Ubuntu Focal 20.04 in Travis tests

---

+bids/query.m
tests/test_bids_query.m

It might be time to remove the remaining `switch`/`case` as there are no special cases any more.

[FIX] Filter subjects and sessions when querying modalities (issue #65)

---

CODE_OF_CONDUCT.md

This is not meant to be a final version in any way but having something is better than nothing. We can try to improve and go beyond the COC of bids-specs with time.

add code of conduct from bids-specs

---

.github/workflows/miss_hit.yml
.travis.yml
README.md
miss_hit.cfg
tests/miss_hit.cfg

For now the rules concerning functions, classes and methods names are ignored.

[INFRA] set up miss_hit linter config and github action

---

miss_hit.cfg

The [MISS_HIT Configuration Guide](https://florianschanda.github.io/miss_hit/configuration.html) recommends putting a `project_root` in your top-level `miss_hit.cfg` file. This will make it play nicely if bids-matlab is included in some other project using MISS_HIT, and maybe optimize the `mh_*` programs' lookup of config files.

miss_hit.cfg: define project_root

---

README.md

MISS_HIT styles their product name in all caps. Should README respect that?
Plus a couple typo/grammar fixes.

README: fix MISS_HIT name styling

---

tests/test_bids_examples.m

Due to new derivatives dataset added in bids-examples:
https://github.com/bids-standard/bids-examples/tree/master/ds000001-fmriprep

Skip datasets when labelled as non-conformant

---

functionSignatures.json
tests/test_functionSignatures.m

I would like to propose a minor Quality of Life improvement (at least for Matlab users - I don't think Octave uses the same mechanism) by providing hints for tab-autocompletion. This can be done by adding a functionSignatures file ([docs](https://www.mathworks.com/help/matlab/matlab_prog/customize-code-suggestions-and-completions.html)), which affects the behavior of Matlab's Command Window, Editor and Live Editor.
The file included in the pull request causes Matlab to:
* autocomplete paths in calls to bids.layout, bids.query and bids.validate
* suggest a choice of 'data', 'metadata', 'sessions' etc. as a second argument to bids.query (typing `bids.query(BIDS, <tab>)` shows the suggestions)
I am not sure if you will consider having autocompletion hints a useful feature, so the provided …

[INFRA] Customize code suggestions & completions by adding a functionSignatures file

---

+bids/+internal/keep_file_for_query.m
+bids/query.m
tests/test_bids_query.m
tests/test_keep_file.m

fix #141 
allows to return only zipped files or tables
```matlab
pth_bids_example = get_test_data_dir();
BIDS = bids.layout(fullfile(pth_bids_example, 'ds007'));
extensions = bids.query(BIDS, 'extensions')
ans =
1×2 cell array
'.nii.gz'    '.tsv'
%%
data = bids.query(BIDS, 'data', ...
'sub', '01', ...
'task', 'stopsignalwithpseudowordnaming', ...
'extension', '.nii.gz', ...
'suffix', 'bold')
ans =
2×1 cell array
'bids-examples/ds007/sub-01/func/sub-01_task-stopsignalwithpseudowordnaming_run-01_bold.nii.gz'
'bids-examples/ds007/sub-01/func/sub-01_task-stopsignalwithpseudowordnaming_run-02_bold.nii.gz'
%%
data = bids.query(BIDS, 'data', ...
'sub', '01', ...
'task', 'stopsignalwithpseudowordnaming', ...
'extension', '.tsv')
ans =
2×1 cell array …
```

[ENH] add possibility to query for (and filter queries with) extensions

---

+bids/+internal/get_metadata.m
+bids/+internal/return_file_index.m
+bids/+internal/return_file_info.m
+bids/+internal/return_subject_index.m
+bids/layout.m
+bids/query.m
tests/test_bids_query.m
tests/test_bids_query_asl.m
tests/test_bids_query_dwi.m
tests/test_bids_query_fmap.m
tests/test_bids_query_func.m
tests/test_bids_query_meg.m
tests/test_get_metadata.m
tests/test_return_file_index.m
tests/test_return_subject_index.m

Does not include a way to query the `intended_for` or `informed_by` field.
---
For reviewers:
This is more on the implementation side, but in terms of "output" I am wondering what would the most useful for users. Ideally, this approach would then be extended to `events` and other "associated files".
- should `informed_by` (pybids uses this I think) replace the `dependencies` field? Which one is more "intuitive"?
See example below
```matlab
BIDS = bids.layout(fullfile(pth_bids_example, 'asl004'));
>> BIDS.subjects.fmap
ans = 
struct with fields:
filename: 'sub-Sub1_dir-pa_m0scan.nii.gz'
ext: '.nii.gz'
suffix: 'm0scan'
entities: [1×1 struct]
meta: [1×1 struct]
intended_for: {'/home/remi/github/BIDS-matlab/tests/bids-examples/asl004/sub-Sub1/perf/sub-Sub1_m0scan.nii.gz'}
>> …
```

[ENH] improve management of "intended_for"

---

+bids/+internal/file_utils.m

Fixed bug described in #165 
It was caused in `canonicalise_path` during reconstruction of path. Linux path was assigned before the check for windows.
This PR fixes it.

Bug in file_utils

---

+bids/+internal/file_utils.m

implement bug fix #166 onto master branch

[HOT FIX] fixed bug in file_utils

---

+bids/+util/jsondecode.m
+bids/+util/jsonencode.m

fixes #176 
Once merged I will also apply this fix on the `dev` branch.

[FIX] lower priority to use SPM function to deal with json files

---

+bids/+internal/get_metadata.m
tests/test_get_metadata.m
tests/test_get_metadata_suffixes.m

Fixes the issue of querying file with metadata files in the root directory (hence sometimes with no "_" before the suffix, like `T1w.json`) while still being able to query files with suffixes that might be part of another suffix: `_thickness.json` and `midthickness.json`.

[FIX] ensures that metadata file have the same prefix as the queried file

---

+bids/+internal/append_to_layout.m
+bids/copy_to_derivative.m
tests/test_parse_filename.m

that can lead to weird bugs and associates the wrong metadata with certain files

[FIX] return empty output of append to layout when failing to parse using schema

---

+bids/schema.m
tests/test_bids_schema.m

The recent extension of the schema leads to:
- invalid matlab fieldnames in the schema content structure
- the loading of over 350 json files when loading the schema which can slow things down if the schema has to be loaded often
This PR:
- ensures that the fieldnames of the content structure are valid
- this is a quick fix and only removes leading underscores and dots (`.`) in the middle of the fieldname
- skip metadata loading by default

[FIX] enforce valid fieldnames in schema content and skip schema metadata loading by default

---

+bids/+internal/keep_file_for_query.m
+bids/+internal/return_file_info.m
+bids/+internal/return_subject_index.m
+bids/copy_to_derivative.m
+bids/layout.m
+bids/query.m
miss_hit.cfg
tests/test_bids_query.m
tests/test_bids_query_eeg.m
tests/test_keep_file.m
tests/test_layout_derivatives.m

Fixes #64 and can now index events.tsv files put in the root folder but still does not index files that can still be put in the subject or session folder.
But this should already cover many datasets.
For the moment `genetic_info.json` file is not indexed because it does not play well `parse_filename`.

[ENH] Index tsv and json files in root folder 

---

+bids/+internal/parse_filename.m
tests/test_parse_filename.m

make sure that parse_filename fails more gracefully when encountering an invalid suffix or an invalid entity-key pair.

add error message to parse_filename

---

+bids/init.m
tests/test_bids_init.m
tests/utils/is_octave.m

Only subjects and sessions labels need to be passed as argument of bids.init for directory structure creation.
Old behavior required to pass the entity-label pairs.

Improve bids.init

---

+bids/+util/plot_events.m
tests/tests_utils/test_plot_events.m

[ENH] Add plot_events for quick dataset visualization

---

+bids/layout.m

- this can be useful when some json files cannot be loaded (see #392)
- this can speed up indexing

[ENH] allow to skip the "manage dependencies" step of the layout

---

+bids/copy_to_derivative.m

closes #467
- adds tolerant parameter to bids.copy_to_derivatives
- set to false by default
- use error handler when there is no data

[FIX] make bids.copy strict by default

---

+bids/layout.m

Changes: added a test if file referenced by IntendedFor field is indexed (if `isempty(info_dest.file_idx)`).
Now it produces warning (if verbose) and skips the file:
```
Warning: IntendedFor file /Storage/beliy/bidsifications/osf/source/sub-01/fmap/sub-01_acq-headMTw_RB1COR.json from sub-01_magnitude1.nii not indexed
```
Removed the try/catch introduced in #471 as it may hide possible bugs and blame input datasets.
This try/catch can be re-introduced, but I feel it must protect full `manage_dependencies` function.
Making request draft, as there an alternative implementation of the fix #474.

[FIX] cleaner handling of missing dependency

---

+bids/+internal/download.m

related to https://github.com/cpp-lln-lab/bidspm/issues/803
demos fails when wget is not present

[FIX] make download more robust when wget is not present

---

+bids/copy_to_derivative.m

Addresses the issue #476 with excessive warnings during the copy to derivative under windows.
Moved warnings in `bids.copy_to_derivatice.m:307` from `if ispc` block to `else` block

Fixes issue #476

---

.github/workflows/update_schema.yml

This will ensure that actions run on the PR. The default `GITHUB_TOKEN` is not enabled to do that to avoid a possible loop of new PRs with actions.

[INFRA] Use PAT to submit pull requests

---

+bids/copy_to_derivative.m
README.md

[DOC] specify the required version of gunzip for copying files on unix system

---

+bids/+util/jsondecode.m
requirements.txt
tests/tests_utils/test_json_decode.m

[ENH] give more meaningful error messsages when failing to read json

---

+bids/copy_to_derivative.m
tests/test_copy_to_derivative.m

[FIX] fix force false skipped when unzipping files

---

+bids/layout.m
tests/tests_layout/test_layout.m

[ENH] improve error message when folder to index does not exist 

---

+bids/+util/tsvwrite.m
tests/tests_utils/test_tsvwrite.m

[FIX] handle nan and and datetimes when printing tables

---

+bids/+util/tsvwrite.m
+bids/copy_to_derivative.m
+bids/layout.m
tests/test_bids_model.m
tests/tests_layout/test_layout.m
tests/tests_layout/test_layout_derivatives.m
tests/tests_private/test_append_to_layout.m
tests/tests_private/test_list_all_trial_types.m
tests/tests_private/test_parse_filename.m
tests/tests_private/test_return_file_index.m
tests/tests_utils/test_create_data_dict.m
tests/tests_utils/test_create_participants_tsv.m
tests/tests_utils/test_create_readme.m
tests/tests_utils/test_create_sessions_tsv.m
tests/utils/skip_if_octave.m

closes #665 
- do not copy participants.tsv to derivativates
- no warning for missing participants.tsv or samples.tsv in derivatives

[ENH] remove checks for participants.tsv or samples.tsv in derivatives

---

+bids/File.m
tests/test_bids_file.m

[ENH] sanitize entities in rename spec

---

+bids/File.m
.vscode/settings.json
docs/source/changelog.md
docs/source/index.rst
tests/test_bids_file.m

[ENH] add zero padding to entity labels / indices when passed as numbers
